title = "Notre-Dame de Paris"
baseURL = "https://lbt666.github.io"
languageCode = "zh"
theme = "ananke"
resourceDir = "./resources"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.zh]
    title = "LBT的个人笔记"
    weight = 100
    contentDir = "content/zh"
  [languages.en]
    title = "Ananke"
    weight = 2
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[services.disqus]
  shortname = 'YOURSHORTNAME'
  
[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 6
  commentoEnable = true

[[params.ananke_socials]]
name = "github"
url = "https://github.com/LBTer"
